app/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

# User table definition
class User(db.Model, UserMixin):
    username = db.Column(db.String(250), primary_key=True)
    email = db.column(db.String(200), unique=True)
    password = db.column(db.String(50))
    isAdmin = db.column(db.Boolean, default=False)
    # Defining relationships
    comments = db.relationship('Comment')
    posts = db.relationship('Post')

# Post table definition
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(1000), nullable=False)
    date = db.Column(db.DateTime(timezone=True), default=func.now()) 
    user_id = db.Column(db.String(250), db.ForeignKey('user.username')) # Foreign key

# Comment table definition
class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    comment = db.column(db.String(1000), nullable=False)
    date = db.Column(db.DateTime(timezone=True), default=func.now()) 
    user_id = db.Column(db.String(250), db.ForeignKey('user.username')) # Foreign key

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from app.routes.auth import auth
from app.routes.post import post
from app.routes.comment import comment
from app.routes.home import home

# defining database
db = SQLAlchemy()
DB_NAME = "forum.db"


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    # Creating blueprints
    app.register_blueprint(post, url_prefix='/post')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(comment, url_prefix='/comment')
    app.register_blueprint(home, url_prefix='/')

    return app

app/routes/auth.py
from flask import Blueprint

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    pass

@auth.route('/logout')
def logout():
    pass

@auth.route('/register')
def register():
    pass

app/routes/comment.py
from flask import Blueprint

comment = Blueprint('comment', __name__)

@comment.route('/add/<id_post>')
def add_comment():
    pass

@comment.route('/delete/<id>')
def delete_comment():
    pass

@comment.route('/update/<id>')
def update_comment():
    pass

app/routes/home.py
from flask import Blueprint, render_template

home = Blueprint('home', __name__)

@home.route('/')
def homepage():
    return render_template("base.html")

@home.route('/searchByTitle')
def searchByTitle():
    return "<h1> RICERCA PER TITOLO </h1>"

@home.route('/searchByDate')
def searchByDate():
    return "<h1> RICERCA PER DATA  </h1>"

app/routes/post.py
from flask import Blueprint

post = Blueprint('views', __name__)

@post.route('/add')
def add_post():
    pass

@post.route('/delete/<id>')
def delete_post():
    pass

@post.route('/update/<id>')
def update_post():
    pass

app/templates/base.html
<!DOCTYPE html>
<!-- This file contains navbar and footer -->
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Loading Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    </head>
    <body>
        <!-- Navbar -->
        <header style="margin-bottom: 20px;">
            <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #24648b;">
                <div class="container-fluid">
                  
                  <!-- Barra di ricerca e pulsante aggiuntivo a sinistra -->
                  <div class="d-flex">
                    <form action="{{ url_for('home.searchByTitle') }}" method="GET" class="d-flex" id="searchForm">
                        <input class="form-control me-2" type="text" name="query" id="searchInput" placeholder="Cerca per titolo">
                        
                        <select class="form-select me-2" id="searchType">
                            <option value="title" selected>Titolo</option>
                            <option value="date">Data</option>
                        </select>
                    
                        <button class="btn btn-light" type="submit">Cerca</button>
                    </form>
                  </div>
            
                    <!-- Pulsante aggiuntivo a sinistra -->
                
              
                  <!-- Bottone di menu (per schermi piccoli) -->
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
              
                  <!-- Pulsanti a destra -->
                  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#" style="color: white;">Admin</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#" style="color: white;">Registrati</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#" style="color: white;">Login</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
        </header>

        <!-- Js script for search field in navbar -->
        <script>
            document.getElementById("searchType").addEventListener("change", function() {
                let input = document.getElementById("searchInput");
                let form = document.getElementById("searchForm");
        
                if (this.value === "date") {
                    input.type = "date";
                    input.placeholder = "Seleziona una data";
                    form.action = "{{ url_for('home.searchByDate') }}";
                } else {
                    input.type = "text";
                    input.placeholder = "Cerca per Titolo...";
                    form.action = "{{ url_for('home.searchByTitle') }}";
                }
            });
        </script>
        <!-- Loading Bootstrap -->
        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
        ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
        ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
        ></script>
    </body>
</html>